version: "3"

services:
  server:
    build: .
    restart: always
    environment:
      - CABINET_URL=
      - MONGO_CONNSTRING=
      - SECRET=
      - ZULIP_URL=
      - BOT_EMAIL=
      - BOT_TOKEN=
    ports:
      - 8000:8000
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
