version: "3"

services:
  server:
    build: .
    restart: always
    environment:
      - CABINET_URL=
      - MONGO_CONNSTRING=
      - SECRET=
    ports:
      - 8000:8000
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    # Volumes ...
