version: "3"

services:
  server:
    image: registry.miem.hse.ru/239/239-application-notifier/server:0.1.1
    restart: always
    environment:
      - CABINET_URL=
      - MONGO_CONNSTRING=
      - SECRET=
    ports:
      - 8000:8000
    depends_on:
      - mongo
  timer:
    image: registry.miem.hse.ru/239/239-application-notifier/timer:0.1.1
    restart: always
    environment:
      - CABINET_URL=
      - MONGO_CONNSTRING=
      - ZULIP_URL=
      - BOT_EMAIL=
      - BOT_TOKEN=
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
