version: "3"

services:
  app:
    build: .
    restart: always
    environment:
      - CABINET_URL=
      - PG_HOST=
      - PG_PORT=
      - PG_USER=
      - PG_PASSWORD=
      - PG_DATABASE=
      - SECRET=
      - ZULIP_URL=
      - BOT_EMAIL=
      - BOT_TOKEN=
      - COOLDOWN=
    depends_on:
      - db
  db:
    image: "postgres:15-alpine"
    restart: always
    volumes:
      - ./pg_data:/var/lib/postgresql/data
